require: rubocop-rails

# Yeah, sorry
Style/HashLikeCase:
  Enabled: true

Style/StringHashKeys:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'bin/*'  
    - 'coverage/**/*'  
    - 'db/**/*'    
    - 'log'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/dummy/db/schema.rb'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Guardfile'
