export default {
  device: 'desktop',
  previewReady: false,
  previewDocument: null,
  site: null,
  theme: null,
  page: null,
  section: null,
  sectionDefinition: null,
  hoveredSection: null,
  sectionBlock: null,
  sectionBlockDefinition: null,
  sections: {},
  sectionBlocks: {},
  editorSettings: {},
}
