#!/usr/bin/env ruby
# frozen_string_literal: true

# This is a wrapper for the tailwindcss-ruby gem to make it easier to use in the Maglev CMS.
# Source: https://github.com/flavorjones/tailwindcss-ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'tailwindcss-ruby', '~> 4.1', '>= 4.1.11'
end

require 'tailwindcss/ruby'

begin
  command = [Tailwindcss::Ruby.executable, *ARGV]
  puts command.inspect
  if Gem.win_platform?
    # use system rather than exec as exec inexplicably fails to find the executable on Windows
    # see related https://github.com/rubys/sprockets-esbuild/pull/4
    system(*command, exception: true)
  else
    exec(*command)
  end
rescue Tailwindcss::Ruby::UnsupportedPlatformException, Tailwindcss::Ruby::ExecutableNotFoundException => e
  warn("ERROR: #{e.message}")
  exit 1
end
