export const page = {
  id: 1,
  title: 'Home page',
  path: 'index',
  layoutId: 'default',
  pathHash: { en: 'index', fr: 'index' },
  visible: true,
  seoTitle: 'My awesome home page',
  metaDescription: null,
  ogTitle: null,
  ogDescription: null,
  ogImageUrl: null,
  previewUrl: '/maglev/preview',
  liveUrl: '/',
  lockVersion: 1,
  translated: true,
}
