# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord-nulldb-adapter'
gem 'lookbook'
gem 'maglevcms', path: '..'
gem 'propshaft'
gem 'puma', '>= 8.0.2'
gem 'rails', '~> 8.1.3'

# Vulnerable gems
gem 'addressable', '>= 2.9.0'
gem 'concurrent-ruby', '>= 1.3.7'
gem 'css_parser', '>= 3.0.0'
gem 'erb', '>= 6.0.4'
gem 'json', '>= 2.19.9'
gem 'loofah', '>= 2.25.2'
gem 'net-imap', '>= 0.6.4.1'
gem 'nokogiri', '>= 1.19.4'
gem 'rack', '>= 3.2.6'
gem 'rack-session', '>= 2.1.2'
gem 'rails-html-sanitizer', '>= 1.7.1'
gem 'websocket-driver', '>= 0.8.2'
gem 'yard', '>= 0.9.44'
