# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord-nulldb-adapter'
gem 'lookbook'
gem 'maglevcms', path: '..'
gem 'propshaft'
gem 'puma', '>= 8.0'
gem 'rails', '~> 8.1.3'

# Vulnerable gems
gem 'addressable', '>= 2.9.0'
gem 'erb', '>= 6.0.4'
gem 'net-imap', '>= 0.6.4'
gem 'rack', '>= 3.2.6'
gem 'rack-session', '>= 2.1.2'
gem 'yard', '>= 0.9.42'
